worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    keepalive_timeout 65;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent"';
    access_log /var/log/nginx/access.log main;

    upstream order_service      { server order-service:8081; }
    upstream market_data        { server market-data:8082; }
    upstream ledger_service     { server ledger-service:8083; }
    upstream wallet_service       { server wallet-service:8084; }
    upstream blockchain_service   { server blockchain-service:8085; }
    upstream auth_service         { server auth-service:8090; }
    upstream user_service         { server user-service:8091; }
    upstream matching_service     { server matching-service:8092; }

    include /etc/nginx/conf.d/*.conf;
}
